### PR TITLE
! kanela-kotlin-extension: Increase API readability

### PR DESCRIPTION
**Pull request by fgaule**
Hi guys! Yesterday @cspinetta show me this cool stuff he was working on, and i couldn't resist to apply some Kotlin features to make you api a little less java-like (more readable).

Please feel free to do or undo whatever i have done.

Cheers!

### CODE REVIEW

**Comment by cspinetta** [comment]
@ivantopo @dpsoft please take a look these really interesting changes

**Comment by dpsoft** [comment]
Hey @fgaule  good to see you here!!!. Thanks for proposing this PR, I really like the changes

**Comment by dpsoft** [comment]
@fgaule listo!!!

**Comment by fgaule** [comment]
:smiley:

**Pull request merged**
